version: '3'
services:
  lf-web:
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - lf:/opt/lf/frontend/config
    #image: 'darkgigabyte/liquid-feedback-docker:latest'
    build: .
    depends_on:
      - db
    env_file:
      - lf.env

  lf-cron:
    restart: unless-stopped
    build: .
    depends_on:
      - db
    env_file:
      - lf.env
    entrypoint: ["/opt/lf/bin/lf_updated"]
    
  db:
    image: 'postgres:9.4-alpine'
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
    env_file:
      - lf.env

volumes:
  lf:
  pg:
